---
# can't merge patch container envs without 
# providing a container image so we query 
# the current one here to provide it in the patch
- name: get current calico-node container image
  command: >
    microk8s kubectl get ds/calico-node
    -o jsonpath='{.spec.template.spec.containers[0].image}'
    --namespace kube-system
  register: calico_node_container_image
  changed_when: false

- name: patch ds/calico-node with IP_AUTODETECTION_METHOD
  kubernetes.core.k8s:
    merge_type: ["merge"]
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: calico-node
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: calico-node
                image: "{{ calico_node_container_image.stdout }}"
                env:
                  - name: IP_AUTODETECTION_METHOD
                    value: "interface={{ vxlan.interface }}"

- name: restart kube-system pods
  command: >
    microk8s kubectl delete pods
    --namespace kube-system
    --all
  changed_when: false
