---
# https://molecule.readthedocs.io/en/latest/configuration.html#scenario
scenario:
  test_sequence:
    - lint
    - syntax
    - destroy
    - create
    - converge
    - idempotence
    - destroy
  create_sequence:
    - lint
    - syntax
    - create
  destroy_sequence:
    - lint
    - syntax
    - destroy
  converge_sequence:
    - lint
    - syntax
    - converge
    - idempotence

# https://molecule.readthedocs.io/en/latest/configuration.html?highlight=requirements#molecule.dependency.ansible_galaxy.AnsibleGalaxy
# https://github.com/ansible-community/molecule/issues/1509
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yaml
    requirements-file: molecule/default/requirements.yaml

driver:
  name: vagrant
  provider:
    name: virtualbox

# ubuntu overview: https://app.vagrantup.com/ubuntu
platforms:
  # 21.10 
  - name: impish-indri
    box: ubuntu/impish64
    memory: 2048
    cpus: 2
  # 21.04
  - name: hirsute-hippo
    box: ubuntu/hirsute64
    memory: 2048
    cpus: 2
  # 20.04 LTS
  - name: focal-fossa
    box: ubuntu/focal64
    memory: 2048
    cpus: 2
  # 18.04 LTS
  - name: bionic-beaver
    box: ubuntu/bionic64
    memory: 2048
    cpus: 2
  # 16.04 LTS
  - name: xenial-xerus
    box: ubuntu/xenial64
    memory: 2048
    cpus: 2

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
