# code: language=ansible
---
- name: Deinstall microk8s
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  vars_prompt:
    - name: sudo_pass
      prompt: "Provide your sudo password to start the deinstallation"

  tasks:
    - name: Stop microk8s
      become: true
      ansible.builtin.command: /snap/bin/microk8s stop
      ignore_errors: true

    - name: Remove snap package
      become: true
      community.general.snap:
        state: absent
        name: microk8s

    - name: Remove current user from microk8s group
      become: true
      ansible.builtin.command: "gpasswd --delete {{ ansible_user }} microk8s"

    - name: Remove conf and created files
      loop:
        - "{{ microk8s_kubeconfig }}"
        - /etc/profile.d/microk8s.sh
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
