---
- name: Deinstall microk8s
  hosts: localhost
  connection: local
  vars_files: vars.yaml
  tasks:
    - name: Stop microk8s
      tags: skip_ansible_lint
      become: true
      ansible.builtin.command: /snap/bin/microk8s stop
      ignore_errors: true

    - name: Remove snap package
      become: true
      community.general.snap:
        state: absent
        name: microk8s

    - name: Remove current user from microk8s group
      become: true
      ansible.builtin.command: "gpasswd --delete {{ ansible_env.USER }} microk8s"

    - name: Remove conf and created files
      become: true
      loop:
        - "{{ microk8s_kubeconfig }}"
        - /etc/profile.d/microk8s.sh
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
