---
- name: install microk8s
  hosts: localhost
  vars_prompt:
    - name: sudo_password
      prompt: "Provide your sudo_password for the play to start"
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/microk8s_config"
  roles:
    - role: install
      tags: ["i", "inst", "install"]
    - role: add-ons
      tags: ["a", "ao", "add-ons"]
    - role: k8s-dashboard
      tags: ["d", "dashboard", "k8s-dashboard"]