---
- name: Install microk8s
  hosts: localhost
  vars_prompt:
    - name: sudo_password
      prompt: "Provide your sudo_password to start the installation"

  vars:
    ansible_connection: local
    ansible_python_interpreter: "/usr/bin/env python3"
    ansible_become_method: sudo
    ansible_sudo_pass: "{{ sudo_password }}"

    microk8s:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/microk8s"
      version: latest/stable
      add_ons:
        - dns
        - rbac
        - hostpath-storage
        - host-access

  tasks:
    - name: Install microk8s
      become: true
      community.general.snap:
        name: microk8s
        classic: true
        channel: "{{ microk8s.version }}"

    - name: Add current user to microk8s group
      become: true
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: microk8s

    - name: Ensure $HOME/.bashrc exists
      become: true
      ansible.builtin.copy:
        content: ""
        dest: "{{ lookup('env', 'HOME') }}/.bashrc"
        force: false
        mode: "0644"
        owner: "{{ lookup('env', 'USER') }}"

    - name: Create aliases
      ansible.builtin.blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        marker: "# {mark} ansible managed by https://github.com/OlGe404/microk8s"
        block: |-
          alias m8s='microk8s'
          alias mkctl='microk8s kubectl'
          export KUBECONFIG='{{ microk8s.kubeconfig }}'

    - name: Get kubeconfig file output
      become: true
      ansible.builtin.command: microk8s kubectl config view --raw
      register: kubeconfig
      changed_when: '"apiVersion: v1" in kubeconfig.stdout'
      failed_when:
        - kubeconfig.rc != 0
        - '"apiVersion: v1" not in kubeconfig.stdout'

    - name: Create kubeconfig file from output
      ansible.builtin.blockinfile:
        path: "{{ microk8s.kubeconfig }}"
        create: true
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0600"
        marker: "# {mark} ansible managed by https://github.com/OlGe404/microk8s"
        block: "{{ kubeconfig.stdout }}"

    - name: Start microk8s
      become: true
      changed_when: false
      ansible.builtin.command: /snap/bin/microk8s.start

    - name: Wait for microk8s to be ready
      become: true
      changed_when: false
      ansible.builtin.command: /snap/bin/microk8s.status --wait-ready

    - name: "Enable microk8s add-ons: {{ microk8s.add_ons | join(', ') }}"
      become: true
      ansible.builtin.command: "microk8s enable {{ item }}"
      register: enable_addon
      changed_when: false
      with_items: "{{ microk8s.add_ons }}"

    - name: Deploy kubernetes-dashboard
      kubernetes.core.k8s:
        namespace: kube-system
        template: "{{ query('fileglob', '{{ playbook_dir }}/kubernetes-dashboard/*.yaml') }}"
        kubeconfig: "{{ microk8s.kubeconfig }}"

    - name: Wait for kubernetes-dashboard rollout
      become: true
      ansible.builtin.command: microk8s kubectl rollout status deploy/k8s-dashboard --namespace kube-system
      register: dashboard_status
      changed_when: '"successfully rolled out" in dashboard_status.stdout'
      until: dashboard_status.rc == 0
      retries: 30
      delay: 10

    - ansible.builtin.debug:
        msg: "You can now access the kubernetes-dashbaord UI at: http://localhost:30001"
      tags:
        - skip_ansible_lint
