# code: language=ansible
---
- name: Install microk8s {{ microk8s_version }}
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  vars_prompt:
    - name: sudo_pass
      prompt: "Provide your sudo password to start the installation"

  tasks:
    - name: Install snap package
      become: true
      community.general.snap:
        name: microk8s
        classic: true
        channel: "{{ microk8s_version }}"

    - name: Add user to microk8s group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups: microk8s

    - name: Create aliases and ENVs
      become: true
      ansible.builtin.blockinfile:
        path: /etc/profile.d/microk8s.sh
        create: true
        owner: root
        group: root
        mode: "0644"
        marker: "{{ ansible_blockinfile_marker }}"
        block: |
          alias mk8s='microk8s'
          alias mkctl='microk8s kubectl'
          alias mkns='_mkns(){ microk8s kubectl config set-context microk8s --namespace "$1" ;}; _mkns'
          export KUBECONFIG='{{ microk8s_kubeconfig }}'

    - name: Get kubeconfig file output
      become: true
      ansible.builtin.command: microk8s kubectl config view --raw
      register: kubeconfig

    - name: Create kubeconfig file from output
      ansible.builtin.blockinfile:
        path: "{{ microk8s_kubeconfig }}"
        create: true
        owner: "{{ ansible_user }}"
        mode: "0600"
        marker: "{{ ansible_blockinfile_marker }}"
        block: "{{ kubeconfig.stdout }}"

    - name: Start microk8s
      become: true
      ansible.builtin.command: /snap/bin/microk8s.start

    - name: Wait for microk8s to be ready
      become: true
      ansible.builtin.command: /snap/bin/microk8s.status --wait-ready

    - name: "Enable microk8s add-ons: {{ microk8s_add_ons | join(', ') }}"
      become: true
      ansible.builtin.command: "microk8s enable {{ item }}"
      with_items: "{{ microk8s_add_ons }}"

    - name: Community addons
      when: microk8s_community_addons|length > 0
      block:
        - name: Enable community addons repo
          become: true
          ansible.builtin.command: microk8s enable community

        - name: "Install community add-ons: {{ microk8s_community_addons | join(', ') }}"
          become: true
          ansible.builtin.command: "microk8s enable {{ item }}"
          with_items: "{{ microk8s_community_addons }}"

    - name: Add kubernetes-dashboard helm repo
      tags: dashboard
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        url: https://kubernetes.github.io/dashboard/
    
    - name: Install kubernetes-dashboard
      tags: dashboard
      kubernetes.core.helm:
        release_name: kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        chart_version: "7.4.0"
        values_files: dashboard-values.yaml

    - name: Wait for kubernetes-dashboard-web rollout to finish
      tags: dashboard
      become: true
      ansible.builtin.command: >
        microk8s kubectl rollout status deploy/kubernetes-dashboard-web
        --namespace kubernetes-dashboard
      register: dashboard_status
      changed_when: '"successfully rolled out" in dashboard_status.stdout'
      until: dashboard_status.rc == 0
      retries: 30
      delay: 10

    - name: Print kubernetes-dashboard infos
      tags: dashboard
      ansible.builtin.debug:
        msg: >-
          You can now access the kubernetes-dashboard at: http://localhost:30001.
          See README.md on how to get the required login token. 
