- name: install and setup microk8s with additional deployments
  hosts: localhost
  vars:
    ansible_python_interpreter: auto
  roles:
    - role: install
      tags: ['install']
    - role: setup
      tags: ['setup']
    - role: jenkins
      tags: ['jenkins']