---
- name: setup local one-node microk8s environment
  hosts: localhost
  vars:
    ansible_python_interpreter: auto
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/microk8s_config"
  roles:
    - role: setup
      tags: ['setup']
    - role: jenkins
      tags: ['jenkins']