---
- name: add codecentric helm repo
  community.kubernetes.helm_repository:
    name: codecentric
    repo_url: "https://codecentric.github.io/helm-charts"

- name: deploy helm chart
  community.kubernetes.helm:
    name: jenkins
    namespace: "{{ jenkins.namespace }}"
    create_namespace: true
    chart_ref: codecentric/jenkins
    chart_version: ~1.7
    update_repo_cache: yes
    wait: yes
    wait_timeout: 1200
    values: "{{ lookup('file', 'values.yaml') | from_yaml }}"
  register: deployed_chart

- name: check deployed_chart
  debug:
    msg: "{{ deployed_chart }}"
    verbosity: 2

- name: deploy templates for monitoring
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  loop: "{{ query('fileglob', 'templates/*.yaml') }}"