---
- name: Install microk8s
  hosts: localhost
  vars_prompt:
    - name: sudo_password
      prompt: "Provide your sudo_password for the play to start"

  roles:
    - role: microk8s
      tags: ["microk8s", "m8s"]
