---
- name: deploy cert-manager resources
  block:
    - name: add jetstack helm repo
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: deploy helm chart
      community.kubernetes.helm:
        name: cert-manager
        namespace: "{{ cert_manager.namespace }}"
        create_namespace: true
        chart_ref: jetstack/cert-manager
        chart_version: ~v1.1
        update_repo_cache: yes
        wait: yes
        values: "{{ lookup('file', 'cert-manager/values.yaml') | from_yaml }}"
      register: deployed_chart

    - name: deploy secret for ca-issuer
      shell: |
        microk8s kubectl create secret tls ingress-ca \
        --cert={{ tls_ca_crt.filename }} \
        --key={{ tls_ca_key.filename }} \
        --namespace {{ cert_manager.namespace }} \
        -o yaml --dry-run=client | microk8s kubectl apply -f -
      args:
        executable: /bin/bash

    - name: deploy templates for ca-issuer and prometheus monitoring
      community.kubernetes.k8s:
        definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
        state: present
      loop: "{{ query('fileglob', 'templates/cert-manager/*.yaml') }}"