---
- name: install dependencies
  block:
    - name: python-pip
      become_method: sudo
      become: true
      apt:
        name: python3-pip
        state: present

    - name: openshift pip-module
      pip:
        name: openshift
        extra_args: --user

    - name: install kubectl
      become_method: sudo
      become: true
      snap:
        name: kubectl
        state: present
        classic: yes

    - name: install helm
      become_method: sudo
      become: true
      snap:
        name: helm
        state: present
        classic: yes

    - name: libnss3-tools for certutil
      become_method: sudo
      become: true
      apt:
        name: libnss3-tools
        state: present