# dependencies.yaml
# microk8s_addons.yaml
# openssl.yaml
# cert_manager.yaml
# ingress.yaml
# k8s_dashboard.yaml

---
- name: include tasks for setup
  include_tasks: "{{ item | array }}"
  loop:
    - dependencies.yaml
    - microk8s_addons.yaml
    - openssl.yaml
    - cert_manager.yaml
    - ingress.yaml
    - k8s_dashboard.yaml
    # - monitoring.yaml