---
- name: create openssl ca certificate to sign ingress wildcard certificate
  block:
    - name: create dir for files
      file:
        path: "{{ lookup('env', 'HOME') }}/microk8s/tls/ca"
        state: directory
      register: tls_ca_dir

    - name: check tls_ca_dir
      debug:
        msg: "{{ tls_ca_dir }}"
        verbosity: 2

    - name: create openssl ca private key
      community.crypto.openssl_privatekey:
        path: "{{ tls_ca_dir.path }}/microk8s_ca.pem"
      register: tls_ca_key

    - name: check tls_ca_key
      debug:
        msg: "{{ tls_ca_key }}"
        verbosity: 2

    - name: create openssl ca certificate signing request
      community.crypto.openssl_csr:
        path: "{{ tls_ca_dir.path }}/microk8s_ca.csr"
        privatekey_path: "{{ tls_ca_key.filename }}"
        country_name: "DE"
        organization_name: "local microk8s CA company"
        common_name: "microk8s.local"
        basic_constraints:
          CA:TRUE
        basic_constraints_critical: yes
        key_usage:
          - digitalSignature
          - keyEncipherment
          - dataEncipherment
          - keyAgreement
          - keyCertSign
        key_usage_critical: yes
      register: tls_ca_csr

    - name: check tls_ca_csr
      debug:
        msg: "{{ tls_ca_csr }}"
        verbosity: 2

    - name: create openssl ca certificate
      community.crypto.x509_certificate:
        path: "{{ tls_ca_dir.path }}/microk8s_ca.crt"
        privatekey_path: "{{ tls_ca_key.filename }}"
        csr_path: "{{ tls_ca_csr.filename }}"
        provider: selfsigned
      register: tls_ca_crt

    - name: check tls_ca_crt
      debug:
        msg: "{{ tls_ca_crt }}"
        verbosity: 2

- name: update-ca-certificates with generated ca-certificate
  become_method: sudo
  become: true
  block:
    - name: copy certificate to local ca-certificates dir
      copy:
        src: "{{ tls_ca_crt.filename }}"
        dest: "/usr/local/share/ca-certificates"
        owner: "{{ lookup('env', 'USER') }}"
        group: root
        mode: 0644
    
    - name: run update-ca-certificates
      command: update-ca-certificates --verbose --fresh
      register: update_ca_certificates

    - debug:
        msg: "{{ update_ca_certificates.stdout }}"
        verbosity: 2

- name: update firefox ca store
  block:
    - name: Find firefox profile dirs
      find:
        paths: "{{ lookup('env', 'HOME') }}/.mozilla/firefox"
        file_type: directory
        use_regex: yes
        patterns: ['.*.default.*']
      register: firefox_profile_dir

    - name: check firefox_profile_dir
      debug:
        msg: "{{ firefox_profile_dir }}"
        verbosity: 2

    - name: import ca certificate into firefox
      shell: |
        certutil -A -n microk8s_ca -t 'TC,,' -i {{ tls_ca_crt.filename }} -d {{ item.path }}
      args:
        executable: /bin/bash
      with_items: "{{ firefox_profile_dir.files }}"

- name: alter hosts file for routing of ingress hosts
  become_method: sudo
  become: true
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} OF ANSIBLE MANAGED BLOCK FOR MICROK8S HOSTS"
    block: |
      127.0.0.1       dashboard.microk8s.local
      127.0.0.1       kibana.microk8s.local
      127.0.0.1       grafana.microk8s.local
      127.0.0.1       prometheus.microk8s.local
      127.0.0.1       alertmanager.microk8s.local
      127.0.0.1       jenkins.microk8s.local