---
name: main
on:
  push:
    branches:
      - main1234

    paths-ignore:
      - .vscode/settings.json
      - .ansible-lint
      - .gitignore
      - deinstall.yaml
      - LICENSE
      - README.md
      - renovate.json

concurrency:
  group: actions
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prerequisites
        run: ./prerequisites.sh
      
      - name: Ansible playbook
        run: ansible-playbook install.yaml
